// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCrTDULC0qLJ4DLD_3ighNcEgKuokgjE',
    appId: '1:561324311728:web:459bde8f9d4fe4b8ac6775',
    messagingSenderId: '561324311728',
    projectId: 'latin-learner',
    authDomain: 'latin-learner.firebaseapp.com',
    storageBucket: 'latin-learner.appspot.com',
    measurementId: 'G-03Q1F434B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChFSBpWG9s6PocrQqMmyRO3KAcVpmkQSQ',
    appId: '1:561324311728:android:1c61b66287d9995fac6775',
    messagingSenderId: '561324311728',
    projectId: 'latin-learner',
    storageBucket: 'latin-learner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05FBfJnuD5bkJuFUw_2LUz11KepsswMQ',
    appId: '1:561324311728:ios:469a8c2980e377c9ac6775',
    messagingSenderId: '561324311728',
    projectId: 'latin-learner',
    storageBucket: 'latin-learner.appspot.com',
    iosBundleId: 'com.owen.devApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05FBfJnuD5bkJuFUw_2LUz11KepsswMQ',
    appId: '1:561324311728:ios:9bb0e7c78297310aac6775',
    messagingSenderId: '561324311728',
    projectId: 'latin-learner',
    storageBucket: 'latin-learner.appspot.com',
    iosBundleId: 'com.example.test2',
  );
}
